import 'package:s_map/interfaces/interfaces.dart';
import 'package:s_map/models/models.dart';

/// Default S-Map map palette. Add another implementation or preset here when
/// the visual language changes; MapLibre widgets do not need to change.
class DefaultMapStyleThemeProvider implements IMapStyleThemeProvider {
  static const MapStylePalette light = MapStylePalette(
    mapBackground: '#F7F9FC',
    landWood: '#DCEBD7',
    landGrass: '#E7F1DE',
    landScrub: '#EEF2DF',
    landWetland: '#DDEEF0',
    landDefault: '#EEF2F6',
    landResidential: '#F0F2F5',
    landCommercial: '#F8EBDD',
    landIndustrial: '#E8EAF0',
    landCemetery: '#E1EFDF',
    landMilitary: '#E8E4EF',
    landuseDefault: '#EEF1F4',
    parkFill: '#DCEED8',
    parkOutline: '#B9D9B4',
    waterFill: '#BFDFF1',
    waterOutline: '#9CC9E4',
    waterwayLine: '#8FC7E6',
    boundaryLine: '#AAB7C6',
    aerowayFill: '#E6E8ED',
    aerowayLine: '#B4BBC7',
    buildingFill: '#D9DFE8',
    buildingOutline: '#C0C9D5',
    roadCasing: '#FFFFFF',
    roadMotorway: '#D9574D',
    roadTrunk: '#E6814B',
    roadPrimary: '#F2B85F',
    roadSecondary: '#FFFFFF',
    roadTertiary: '#FFFFFF',
    roadMinor: '#FFFFFF',
    roadService: '#E5E9EE',
    roadTrack: '#D8C39B',
    roadDefault: '#FFFFFF',
    placeDot: '#6C7B8A',
    placeStroke: '#FFFFFF',
    poiDot: '#607D8B',
    poiStroke: '#FFFFFF',
    houseNumberDot: '#7B8794',
    labelPrimary: '#374151',
    labelSecondary: '#596579',
    labelWater: '#2E759C',
    labelPoi: '#4B5563',
    labelHalo: '#F7F9FC',
  );

  static const MapStylePalette dark = MapStylePalette(
    mapBackground: '#111827',
    landWood: '#1D382F',
    landGrass: '#243B35',
    landScrub: '#303D35',
    landWetland: '#203E4B',
    landDefault: '#1A2433',
    landResidential: '#202B3B',
    landCommercial: '#3A3032',
    landIndustrial: '#2D303D',
    landCemetery: '#263A34',
    landMilitary: '#302C40',
    landuseDefault: '#202A38',
    parkFill: '#1E3C32',
    parkOutline: '#315B48',
    waterFill: '#183B54',
    waterOutline: '#255A79',
    waterwayLine: '#3E91B8',
    boundaryLine: '#5F7891',
    aerowayFill: '#2D3441',
    aerowayLine: '#536276',
    buildingFill: '#2A3546',
    buildingOutline: '#3E4C60',
    roadCasing: '#172131',
    roadMotorway: '#E27672',
    roadTrunk: '#E6A16C',
    roadPrimary: '#E8C37A',
    roadSecondary: '#AAB8C8',
    roadTertiary: '#93A5B8',
    roadMinor: '#7F92A6',
    roadService: '#66788C',
    roadTrack: '#8C7954',
    roadDefault: '#8FA1B3',
    placeDot: '#B8C5D2',
    placeStroke: '#182333',
    poiDot: '#8CA9BF',
    poiStroke: '#172131',
    houseNumberDot: '#8A9AAF',
    labelPrimary: '#E5EDF5',
    labelSecondary: '#B7C7D8',
    labelWater: '#82C4E5',
    labelPoi: '#D0DCE8',
    labelHalo: '#111827',
  );

  @override
  MapStylePalette paletteFor({required bool isDarkMode}) =>
      isDarkMode ? dark : light;
}
