// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKXo2tcww6Zt4G4ndxMELYsKrWvuX5VGI',
    appId: '1:779346109460:android:11b0bd1bdd7dd8629b7301',
    messagingSenderId: '779346109460',
    projectId: 'boilerplate-aaron-tech',
    storageBucket: 'boilerplate-aaron-tech.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvlC92QkF6Cee5lnBjyaEG-Zv5lZbTYXw',
    appId: '1:779346109460:ios:43c1a3e120f0b4dd9b7301',
    messagingSenderId: '779346109460',
    projectId: 'boilerplate-aaron-tech',
    storageBucket: 'boilerplate-aaron-tech.appspot.com',
    iosBundleId: 'com.aarontech.boilerplate.dev',
  );
}
