// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd3_1M-0IErOc-NdHjC9mgAdS03Cx7DHQ',
    appId: '1:495182969568:android:c4083fca783d0d9cd46e85',
    messagingSenderId: '495182969568',
    projectId: 'vn-s-map',
    storageBucket: 'vn-s-map.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvlC92QkF6Cee5lnBjyaEG-Zv5lZbTYXw',
    appId: '1:779346109460:ios:43c1a3e120f0b4dd9b7301',
    messagingSenderId: '779346109460',
    projectId: 'vn-s-map',
    storageBucket: 'vn-s-map.appspot.com',
    iosBundleId: 'com.vnsmap.app',
  );
}
